services:
  # Backend API Service
  - type: web
    name: wallet-app-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false

  # Frontend Service
  - type: web
    name: wallet-app-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://wallet-app-backend.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
